### ISSUE TITLE
What does the package offer over the standard material design lite

### ISSUE THREAD

**Issue by 6gsaifulislam** [jadjoubran/angular-material-design-lite#2]
I have spent most of the day converting my project from Angular Material over to the new release of material design lite - and it seems to be working very well -  in fact a lot better than the Angular design version.

As it seems to be working well, could you explain what benefits using your angular-material-design-lite would bring?

**Comment by jadjoubran** [comment]
Hi @JohnAReid 
Thanks for taking the time and opening an issue here!

Could you please elaborate more on the first paragraph?
What were the problems that you faced while working with Angular Material Design Lite?

Material Design Lite is distributed with Vanilla JS and Vanilla CSS (no external dependencies). So of course it doesn't make sense to use angularjs for Material Design Lite to work. But if you're already using AngularJS in your app for other various tasks, then this package would be very helpful.

Angular Material Design Lite is an angular wrapper on top of Material Design Lite.
The concept is very similar to this [package](https://github.com/angular-ui/bootstrap).
While keeping in mind that this package is still under development, first of all it offers help by providing a set of directives in order to use the material design components.

As you can see in the Directives section of the documentation: http://jadjoubran.github.io/angular-material-design-lite you can use`<mdl-button-raised theme="primary">Primary Raised button</mdl-button-raised>` instead of the following code:

```
<button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
Button
</button>
```

Awaiting your response!

**Comment by jadjoubran** [comment]
Another planned feature is the mdl-progress directive which wraps mdl's progress bar.  
It would be extremely helpful to use it through angular material design lite if you want to control the `progress` from your controller:

<mdl-progress progress="60"></mdl-progress>

and then everytime you change the vaue of progress, it'll automatically update the loader.

**Comment by 6gsaifulislam** [comment]
Could you please elaborate more on the first paragraph?
I have been using Angular Material for the last six months or so - and mainly on the whole happy with it, but recently found it is getting hard and harder to control - for example the icon button has a fixed height, a min height and a line height - hence the button takes up a lot of room - converted to the lite version today and it nice and small with no excess padding. In short you had to do things the way Angular Material wanted. I also stopped using features such as the bottom sheet as the layout would change from column to row  whilst the sheet was being opened and it just looked bad. Icons - in Angular Material you had to configure mdIconProvider whilst with the new lite version it is so easy.

If I read your reply correctly angular-material-design is taking the MDL controls and is using directives to make it easier to write and understand. Whilst this will make it a lot easier and faster to use, I personally would prefer to use  MDL directly as least then I have full control when something goes wrong.

**Comment by jadjoubran** [comment]
Sounds great, thanks for your reply!
Well I've also been using Angular Material for about 6 months and I'm loving it so far.
I also open sourced my [Laravel and angular material starter project](http://github.com/jadjoubran/laravel5-angular-material-starter).

So regarding the `Angular Material` and `Material Design Lite` it really depends on your design requirements & functionality. For example I won't be able to work without Angular Material's dialog functionality, but that could be completely useless for you.

Back to angular-material-design, yes it allows you to use directives to easily access MDL components. I'm working on a way to pass all attributes this package's directives to the generated MDL components.
I'd recommend that you check this package in a week or two. It'll be feature complete.
I'd also appreciate it if you can star this repository in order to support it.

And I'd be happy to answer any question you have about this repository or about MDL in general.

**Comment by jadjoubran** [comment]
And don't forget that even if you're using angular-material-design-lite, you can always use the native MDL components instead of the provided directives

**Comment by 6gsaifulislam** [comment]
Thanks for the quick reply - I think what you are doing it great - star added.
